/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemahospitalar;

/**
 *
 * @author luca0
 */
public class TelaPrincipal extends javax.swing.JFrame {
    // Deixarei comentários para os forasteiros que passarem por aqui.
    /**
     * Creates new form TelaPrincipal
     *
     */
    public TelaPrincipal() {
        initComponents(); // Nunca apaguem essa linha.
        carregarTabela(); // é pra atualizar

        // não entendi até agora, mas isso instancia o modelo da tabela
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // obs: isso limpa a tabela :)
        modeloTabela.setRowCount(0);

        try {
            ConectorDB conector = new ConectorDB("jdbc:mysql://localhost:3306/projeto", "root", "root");
            PacienteDAO dao = new PacienteDAO(conector);

            java.util.List<Paciente> pacientesDoBanco = dao.listarPacientes();

            for (Paciente p : pacientesDoBanco) {
                modeloTabela.addRow(new Object[]{
                    p.getId_paciente(),
                    p.getNome_paciente(), 
                    p.getSobrenome(),     
                    p.getGenero(),        
                    p.getData_nascimento(),
                    p.getNumero_quarto(), 
                    p.getTelefone_familia(),
                    p.getMedico(),         
                    p.getTelefone_medico() 
                });
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "erro ao carregar os pacinetes do banco: " + ex.getMessage());
        }
    }
    public void carregarTabela() {
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modeloTabela.setRowCount(0); // Limpa a tabela velha

        try {
            ConectorDB conector = new ConectorDB("jdbc:mysql://localhost:3306/projeto", "root", "root");
            PacienteDAO dao = new PacienteDAO(conector);

            for (Paciente p : dao.listarPacientes()) {
                modeloTabela.addRow(new Object[]{
                    p.getId_paciente(),
                    p.getNome_paciente(),
                    p.getSobrenome(),
                    p.getGenero(),
                    p.getData_nascimento(),
                    p.getNumero_quarto(),
                    p.getTelefone_familia(),
                    p.getMedico(),
                    p.getTelefone_medico()
                });
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao recarregar a tabela: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar Pacientes:");

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Sobrenome", "Gênero", "Data Nasc.", "Quarto", "Tel. Família", "Médico", "Tel. Médico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Novo Paciente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Gerenciar Remédios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Excluir Selecionado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 344, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ESSE BOTÃO É PRA PESQUISA/BUSCAR
        String busca = txtBusca.getText(); 

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // Nota pessoal: O "javax.swing.table.TableRowSorter" é o jeito que o swing faz buscas, se não, teria que mexer no mySQL
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(modelo);
        jTable1.setRowSorter(sorter);

        if (busca.trim().length() == 0) {
            // se o input de busca estiver vazio ele mostra tudo
            sorter.setRowFilter(null); 
        } else {
            // Se tiver texto, ele filtra. 
            // O "(?i)" manda o java ignorar maiusculas e minusculas
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + busca));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Isos é usado no swing para chamar a tela de cadastro. O "true" bloqueia a tela de trás.
        TelaCadastro tela = new TelaCadastro(this, true); 
        tela.setLocationRelativeTo(null); // Centraliza na tela
        tela.setVisible(true); // Faz a tela aparecer
        
        carregarTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Botão de gerenciar remédios
        int linhaSelecionada = jTable1.getSelectedRow(); 

        // -1 significa que o usuário não clicou e ngm
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "selecione um paciente na tabela");
            return;
        }

       
        int id = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());
        // Isso aqui faz ele pegar o nome e sobrenome na linha da tabela, eu quero que ao abrir
        // gerenciar medicamentos ele mostre o nome de quem está sendo editado.
        String nome = jTable1.getValueAt(linhaSelecionada, 1).toString();
        String sobrenome = jTable1.getValueAt(linhaSelecionada, 2).toString();

        TelaMedicamentos tela = new TelaMedicamentos(this, true, id, nome, sobrenome);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Botão de editar
        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "selecione um paciente na tabela");
            return;
        }

        // Pega os textos de cada coluna da linha selecionada
        int id = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
        String nome = jTable1.getValueAt(linha, 1).toString();
        String sobrenome = jTable1.getValueAt(linha, 2).toString();
        String genero = jTable1.getValueAt(linha, 3).toString();
        String data = jTable1.getValueAt(linha, 4).toString();
        String quarto = jTable1.getValueAt(linha, 5).toString();
        String telFam = jTable1.getValueAt(linha, 6).toString();
        String medico = jTable1.getValueAt(linha, 7).toString();
        String telMed = jTable1.getValueAt(linha, 8).toString();

        TelaEdicaoPaciente telaEdit = new TelaEdicaoPaciente(this, true);

        telaEdit.carregarDados(id, nome, sobrenome, genero, data, quarto, telFam, medico, telMed);

        telaEdit.setLocationRelativeTo(null);
        telaEdit.setVisible(true);
        
        carregarTabela();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Botão excluir
        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "selecione um paciente na tabela");
            return;
        }

        int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());

                ConectorDB conector = new ConectorDB("jdbc:mysql://localhost:3306/projeto", "root", "root");
                PacienteDAO dao = new PacienteDAO(conector);

                dao.excluirPaciente(id);

                // Isso que apaga. "removeRow"
                ((javax.swing.table.DefaultTableModel) jTable1.getModel()).removeRow(linha);
                javax.swing.JOptionPane.showMessageDialog(this, "Excluído com sucesso!");

            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
