/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.sistemahospitalar;

/**
 *
 * @author luca0
 */
public class TelaEdicaoMedicamento extends javax.swing.JDialog {
    public int idMedicamento = 0;
    public int idPaciente = 0;
    public java.time.LocalDateTime ultimaDose = null;

    /**
     * Creates new form TelaEdicaoMedicamento
     */
    public TelaEdicaoMedicamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void carregarDados(Medicamento remedio) {
        this.idMedicamento = remedio.getId_medicamento();
        this.idPaciente = remedio.getId_paciente();
        this.ultimaDose = remedio.getUltima_dose();

        txtNomeRemedio.setText(remedio.getNome_medicamento());
        txtTipoMedicamento.setText(remedio.getTipo_medicamento());

        // Desmembra frequencia (em minutos totais) nos três campos
        int totalMinutos = remedio.getFrequencia();
        int dias  = totalMinutos / (60 * 24);
        int horas = (totalMinutos % (60 * 24)) / 60;
        int mins  = totalMinutos % 60;
        txtFrequenciaDias.setText(String.valueOf(dias));
        txtFrequenciaHoras.setText(String.valueOf(horas));
        txtFrequenciaMinutos.setText(String.valueOf(mins));

        txtInstrucoes.setText(remedio.getInstrucoes());
        txtMotivoUso.setText(remedio.getMotivo_uso());
        txtDosesRestantes.setText(String.valueOf(remedio.getDoses_restantes()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInstrucoes = new javax.swing.JTextField();
        txtTipoMedicamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDosesRestantes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFrequenciaDias = new javax.swing.JTextField();
        txtFrequenciaHoras = new javax.swing.JTextField();
        txtFrequenciaMinutos = new javax.swing.JTextField();
        jLabelDias = new javax.swing.JLabel();
        jLabelHoras = new javax.swing.JLabel();
        jLabelMinutos = new javax.swing.JLabel();
        txtNomeRemedio = new javax.swing.JTextField();
        txtMotivoUso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nome do Remédio:");
        jLabel3.setText("Frequência:");
        jLabel4.setText("Motivo de Uso:");

        jLabelDias.setText("d");
        jLabelHoras.setText("h");
        jLabelMinutos.setText("min");

        jLabel5.setText("Via de Administração:");
        jLabel6.setText("Instruções:");
        jLabel7.setText("Doses Restantes:");

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFrequenciaDias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelDias)
                        .addGap(6, 6, 6)
                        .addComponent(txtFrequenciaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelHoras)
                        .addGap(6, 6, 6)
                        .addComponent(txtFrequenciaMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelMinutos))
                    .addComponent(txtMotivoUso, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDosesRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFrequenciaDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDias)
                            .addComponent(txtFrequenciaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHoras)
                            .addComponent(txtFrequenciaMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMinutos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMotivoUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtInstrucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDosesRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // botão editar
        try {
            String nome = txtNomeRemedio.getText();
            String tipo = txtTipoMedicamento.getText();
            String instrucoes = txtInstrucoes.getText();
            String motivo = txtMotivoUso.getText();

            // Combina dias, horas e minutos em minutos totais
            int dias = 0, horas = 0, mins = 0;
            if (!txtFrequenciaDias.getText().trim().isEmpty())
                dias = Integer.parseInt(txtFrequenciaDias.getText().trim());
            if (!txtFrequenciaHoras.getText().trim().isEmpty())
                horas = Integer.parseInt(txtFrequenciaHoras.getText().trim());
            if (!txtFrequenciaMinutos.getText().trim().isEmpty())
                mins = Integer.parseInt(txtFrequenciaMinutos.getText().trim());
            int frequencia = dias * 60 * 24 + horas * 60 + mins;

            int doses = -1;
            if (!txtDosesRestantes.getText().trim().isEmpty()) {
                doses = Integer.parseInt(txtDosesRestantes.getText().trim());
            }

            Medicamento remedioEditado = new Medicamento(this.idMedicamento, this.idPaciente, nome, tipo, instrucoes, frequencia, this.ultimaDose, doses, motivo);

            ConectorDB conector = new ConectorDB("jdbc:mysql://localhost:3306/hospital", "root", "root"); //Substitua o url, usuario e senha pelo seu URL, usuário e senha do MySQL
            MedicamentoDAO dao = new MedicamentoDAO(conector);
            dao.atualizarMedicamento(remedioEditado);

            javax.swing.JOptionPane.showMessageDialog(this, "Remédio atualizado com sucesso!");
            this.dispose();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEdicaoMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEdicaoMedicamento dialog = new TelaEdicaoMedicamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelMinutos;
    private javax.swing.JTextField txtDosesRestantes;
    private javax.swing.JTextField txtFrequenciaDias;
    private javax.swing.JTextField txtFrequenciaHoras;
    private javax.swing.JTextField txtFrequenciaMinutos;
    private javax.swing.JTextField txtInstrucoes;
    private javax.swing.JTextField txtMotivoUso;
    private javax.swing.JTextField txtNomeRemedio;
    private javax.swing.JTextField txtTipoMedicamento;
}